---
- name: Build apache_docker image
  docker_image:
    name: quirioo/apache
    state: present

- name: Start apache_docker container
  docker_container:
    name: apache
    image: quirioo/apache
    state: started
    network_mode: host
